---
title: "Viz part 1"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)
```

```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

Get data for plotting:
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors( # pulling 3 monitors
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```


Make a plot:
```{r}
ggplot(weather_df,aes(x = tmin, y = tmax)) + 
  geom_point()
```

Pipes and stuff:
```{r}
weather_df |> 
  filter(name == "CentralPark_NY") |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()


ggp_nyc_weather = 
  weather_df |> 
  filter(name == "CentralPark_NY") |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
#doesn't print plot, need to call it
```


## Fancy Plot
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.3) + 
  geom_smooth(se = FALSE)

# alpha makes points 30% opaque and 70% transparent
```


Plot with facets
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.3) + 
  geom_smooth()
#still too much going onso can add facet() to separate by name

ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.3) + 
  geom_smooth() + 
  facet_grid(. ~ name)
```


Another Plot:
```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = 0.3) + 
  geom_smooth() + # adds line through points
  facet_grid(. ~ name) # separates into each graph by name
```

Assigning different colors
```{r}
weather_df |> 
  filter(name == "CentralPark_NY") |> 
  ggplot(aes(x = date, y = tmax)) + 
  geom_point(color = "blue", size = .5)
```

Hex Plot
```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_hex()
```

line graph
```{r}
weather_df |> 
  filter(name == "Molokai_HI") |> 
  ggplot(aes(x = date, y = tmax)) +
  geom_line(alpha = .5) + 
  geom_point(size = .5)
```


## Univariate Plotting

Histogram
```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram(position = "dodge")
```


Density plot
```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_density(alpha = .3, adjust = .75) #adjust lets you control how smooth the graph can be
```


Boxplots
```{r}
ggplot(weather_df, aes(y = tmax, x = name)) + 
  geom_boxplot()
```


Violin Plots
```{r}
ggplot(weather_df, aes(y = tmax, x = name)) + 
  geom_violin()
```


Ridge Plot
```{r}
ggplot(weather_df, aes(x = tmax, y = name)) + 
  geom_density_ridges()
```


## saving and embedding plots
```{r}
ggp_weather = 
  weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

ggp_weather

ggsave("saved stuff/ggp_weather.pdf", ggp_weather)
```

```{r, fig.width=12, fig.height=12}
ggp_weather
```
























